points:
    key:
        padding: cy
    zones:
        main:
            rows:
                bottom:
                    row_net: P2
                home:
                    row_net: P0
                top:
                    row_net: P1
                number:
                    row_net: P11
            columns:
                extra_pinky:
                    key:
                        col_net: P10
                        spread: cx
                    rows:
                        bottom:
                        home:
                        top:
                pinky:
                    key:
                        col_net: P7
                        spread: cx
                    rows:
                        bottom:
                        home:
                        top:
                ring:
                    key:
                        col_net: P6
                        stagger: 4
                        spread: cx
                    rows:
                        bottom:
                        home:
                        top:
                middle:
                    key:
                        col_net: P5
                        stagger: 2
                        spread: cx
                    rows:
                        bottom:
                        home:
                        top:
                index:
                    key:
                        col_net: P4
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                        home:
                        top:
                inner:
                    key:
                        col_net: P3
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                        home:
                        top:
        thumb:
            anchor:
                ref: main_inner_bottom
                shift: [-0.5cx, -cy]
            rows:
                home:
                    row_net: P8
            columns:
                inner:
                    key:
                        col_net: P5
                        spread: cx
                home:
                    key:
                        col_net: P4
                        spread: cx + 2
                        rotate: -18
                        stagger: -3.2
                outer:
                    key:
                        col_net: P3
                        spread: cx
                        rotate: -36
                        stagger: -9.2
        thumb2:
            anchor:
                ref: thumb_inner_home
                shift: [0.25cx, -cy-2]
            rows:
                home:
                    row_net: P8
            columns:
                left:
                    key:
                        col_net: P5
                        #spread: cx
                        rotate: -9
                right:
                    key:
                        col_net: P4
                        spread: cx + 4
                        rotate: -36
                        stagger: -3.2-6

outlines:
    _board_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: thumb_outer_home
                    shift: [0.6cx, 0.6cy]
                -   ref: thumb_outer_home
                    shift: [0.6cx, -0.4cy]
#                -   ref: thumb_outer_home
#                    shift: [-0.4cx, -0.6cy]
                -   ref: thumb2_right_home
                    shift: [0.6cx, +0.4cy]
                -   ref: thumb2_right_home
                    shift: [+0.6cx, -0.6cy]
                -   ref: thumb2_right_home
                    shift: [-0.4cx, -0.6cy]
                -   ref: thumb2_left_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb2_left_home
                    shift: [-0.6cx, -0.6cy]
#                -   ref: thumb_home_home
#                    shift: [0.4cx, -0.6cy]
#                -   ref: thumb_home_home
#                    shift: [-0.4cx, -0.6cy]

#                -   ref: thumb_inner_home
#                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_inner_home
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_extra_pinky_bottom
                    shift: [1.6cx, -0.6cy]
                -   ref: main_extra_pinky_bottom
                    shift: [0.6cx, -0.6cy]
                -   ref: main_extra_pinky_bottom
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_extra_pinky_number
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_extra_pinky_number
                    shift: [0.4cx, 0.6cy]

                -   ref: main_ring_number
                    shift: [-0.5cx, 0.6cy]
                -   ref: main_ring_number
                    shift: [0.4cx, 0.6cy]

                -   ref: main_middle_number
                    shift: [-0.4cx, 0.61cy]
                -   ref: main_middle_number
                    shift: [0.4cx, 0.6cy]

                -   ref: main_index_number
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_index_number
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_number
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_inner_number
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_number
                    shift: [0.6cx, 0.4cy]
                -   ref: main_inner_top
                    shift: [1.8cx, 0.4cy]

                -   ref: main_inner_bottom
                    shift: [1.8cx, -0.6cy]
    _keycap_outlines:
        -   what: rectangle
            fillet: 2
            where: true
            size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
    preview:
        -   what: outline
            name: _board_outline
            operation: stack
        -   what: outline
            name: _keycap_outlines
            operation: stack
cases.josukey:
    -   what: outline
        name: _board_outline
        extrude: 3
        operation: subtract
    -   what: outline
        name: _keycap_outlines
        extrude: 6
        operation: add
pcbs.josukey:
    outlines:
        main.outline: _board_outline
        keycaps:
            outline: _keycap_outlines
            layer: Eco1.User
    footprints:
        diode:
            what: sod-123w
            where: true
            params:
                from: "{{name}}"
                to: "{{row_net}}"
            adjust:
                shift: [ -7.6, -1.6 ]
                rotate: 90
        choc:
            what: choc
            where: true
            params:
                keycaps: true
                reverse: true
                hotswap: true
                from: "{{col_net}}"
                to: "{{name}}"
        promicro:
            what: promicro_pretty
            where:
                ref: main_inner_home
            adjust:
                shift: [22, 6.5]
                rotate: -90
       # jst-s2b-ph-kl:
       #     what: jst-s2b-ph-kl
       #     where:
       #         ref: main_inner_bottom
       #         shift: [21, -2]
        #        rotate: 180
        #   params:
        #       neg: GND
#        TRRS:
#            what: trrs_pj320a
#            where:
#                ref: main_inner_bottom
#                shift: [-60, -60]
#                rotate: 90
#            params:
#                side: f
#                reversible: true
#                symmetric: false
#                SL: P2
#                R2: P3
#                R1: P1
#                TP: P4
        TRRS:
            what: trrs
            where:
                ref: main_inner_bottom
                shift: [30.5, -2.5-5]
                rotate: -90
            params:
                designator: 'TRRS'
                reverse: true
                symmetric: false
                A: undefined
                B: undefined
                C: undefined
                D: undefined
#        pcm12: #an aus schalter
#            what: pcm12
#            where:
#                ref: main_inner_bottom
#                shift: [30.5, 3]
#                rotate: 90
#            params:
#                from: pos
#                to: RAW
        wuerth-434121025816:
            what: wuerth-434121025816
            where:
                ref: main_inner_bottom
                shift: [22, 3]
                rotate: 0
            params:
                r1: RST
                r2: GND        

